services:
  # API
  api:
    build: "./api"
    ports: -"3000:3000"
    environment:
      MONGO_URI: mongodb://root:example@db:27017/voltaic-db?authSource=admin
    env_file:
      - ./api/.env
    depends_on:
      - mongodb
      - mysql
    volumes:
      - ./api:/app
      - /app/node_modules

  # Mongo Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  # MySQL Database
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: voltaic-db
